<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>MySQL error</title>
    <link>https://forum.moparisthebest.com/t/mysql-error/394454</link>
    <description>I get this error after I couldn&#39;t log into my phpmyadmin, so I typed [code]sudo /opt/lampp/lampp security[/code] Then, I changed the passwords, now I changed them back, but I get this error on the server. [code=java]com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused

STACKTRACE:

java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
	at java.net.Socket.connect(Socket.java:546)
	at java.net.Socket.connect(Socket.java:495)
	at java.net.Socket.&lt;init&gt;(Socket.java:392)
	at java.net.Socket.&lt;init&gt;(Socket.java:235)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:173)
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:267)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2739)
	at com.mysql.jdbc.Connection.&lt;init&gt;(Connection.java:1553)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at SQL.createConnection(SQL.java:13)
	at server.run(server.java:280)
	at java.lang.Thread.run(Thread.java:679)


** END NESTED EXCEPTION **



Last packet sent to the server was 143 ms ago.
	at com.mysql.jdbc.CommunicationsException.fillInStackTrace(CommunicationsException.java:65531)
	at java.lang.Throwable.&lt;init&gt;(Throwable.java:198)
	at java.lang.Exception.&lt;init&gt;(Exception.java:46)
	at java.sql.SQLException.&lt;init&gt;(SQLException.java:140)
	at com.mysql.jdbc.CommunicationsException.&lt;init&gt;(CommunicationsException.java:56)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2814)
	at com.mysql.jdbc.Connection.&lt;init&gt;(Connection.java:1553)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at SQL.createConnection(SQL.java:13)
	at server.run(server.java:280)
	at java.lang.Thread.run(Thread.java:679)[/code] Any help please?  I&#39;m using the correct username and password.  Linux Ubuntu 11.04, Lampp 1.7.1, DeltaScape base.
[b]EDIT:[/b]Idk what I did, I tried restarting and everything.
Security:[code]
	
Subject	
Status	

	These XAMPP pages are no longer accessible by network for everyone	 SECURE 	 

	MySQL is no longer accessible over the network	 SECURE 	 

	The phpMyAdmin user pma has no longer no password	 SECURE 	 

	The MySQL user root has no longer no password	 SECURE 	 

	The FTP password for user nobody is no langer &#39;lampp&#39;	 SECURE 	[/code]</description>
    
    <lastBuildDate>Tue, 10 May 2011 04:13:49 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/mysql-error/394454.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>MySQL error</title>
        <dc:creator><![CDATA[@sageofmali sageofmali]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/sageofmali">@sageofmali</a> wrote:</p>
          <blockquote>
              <p>I get this error after I couldn’t log into my phpmyadmin, so I typed <code>sudo /opt/lampp/lampp security</code> Then, I changed the passwords, now I changed them back, but I get this error on the server. [code=java]com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception:</p>
<p>** BEGIN NESTED EXCEPTION **</p>
<p>java.net.ConnectException<br>
MESSAGE: Connection refused</p>
<p>STACKTRACE:</p>
<p>java.net.ConnectException: Connection refused<br>
at java.net.PlainSocketImpl.socketConnect(Native Method)<br>
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)<br>
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)<br>
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)<br>
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)<br>
at java.net.Socket.connect(Socket.java:546)<br>
at java.net.Socket.connect(Socket.java:495)<br>
at java.net.Socket.(Socket.java:392)<br>
at java.net.Socket.(Socket.java:235)<br>
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:173)<br>
at com.mysql.jdbc.MysqlIO.(MysqlIO.java:267)<br>
at com.mysql.jdbc.Connection.createNewIO(Connection.java:2739)<br>
at com.mysql.jdbc.Connection.(Connection.java:1553)<br>
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)<br>
at java.sql.DriverManager.getConnection(DriverManager.java:620)<br>
at java.sql.DriverManager.getConnection(DriverManager.java:200)<br>
at SQL.createConnection(SQL.java:13)<br>
at server.run(server.java:280)<br>
at java.lang.Thread.run(Thread.java:679)</p>
<p>** END NESTED EXCEPTION **</p>
<p>Last packet sent to the server was 143 ms ago.<br>
at com.mysql.jdbc.CommunicationsException.fillInStackTrace(CommunicationsException.java:65531)<br>
at java.lang.Throwable.(Throwable.java:198)<br>
at java.lang.Exception.(Exception.java:46)<br>
at java.sql.SQLException.(SQLException.java:140)<br>
at com.mysql.jdbc.CommunicationsException.(CommunicationsException.java:56)<br>
at com.mysql.jdbc.Connection.createNewIO(Connection.java:2814)<br>
at com.mysql.jdbc.Connection.(Connection.java:1553)<br>
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)<br>
at java.sql.DriverManager.getConnection(DriverManager.java:620)<br>
at java.sql.DriverManager.getConnection(DriverManager.java:200)<br>
at SQL.createConnection(SQL.java:13)<br>
at server.run(server.java:280)<br>
at java.lang.Thread.run(Thread.java:679)[/code] Any help please?  I’m using the correct username and password.  Linux Ubuntu 11.04, Lampp 1.7.1, DeltaScape base.<br>
<span class="bbcode-b">EDIT:</span>Idk what I did, I tried restarting and everything.<br>
Security:[code]</p>
<p>Subject	<br>
Status</p>
<pre><code>These XAMPP pages are no longer accessible by network for everyone	 SECURE 	 

MySQL is no longer accessible over the network	 SECURE 	 

The phpMyAdmin user pma has no longer no password	 SECURE 	 

The MySQL user root has no longer no password	 SECURE 	 

The FTP password for user nobody is no langer 'lampp'	 SECURE 	[/code]</code></pre>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/mysql-error/394454/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/mysql-error/394454/1</link>
        <pubDate>Tue, 10 May 2011 04:13:49 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-394454-1</guid>
        <source url="https://forum.moparisthebest.com/t/mysql-error/394454.rss">MySQL error</source>
      </item>
  </channel>
</rss>
