<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Exception encountered while trying to wear something</title>
    <link>https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201</link>
    <description>Okay this might sound stupid, i was messing with my stuff cleaning blabla, and i saw the boolean wear and then i said, i&#39;ll move it to wearing.java l0l and then when i moved it it would throw me an exception so i moved it back to the client and then it&#39;s throwing me the same excp..[code=java]xception encountered while parsing incoming packets from Mr boogie.
java.lang.NullPointerException
	at server.oblivion2.player.Special.needSpecial(Special.java:136)
	at server.oblivion2.player.Client.wear(Client.java:2605)
	at server.oblivion2.player.Packets.parseIncomingPackets(Packets.java:5438)
	at server.oblivion2.player.Client.packetProcess(Client.java:9889)
	at server.oblivion2.player.PlayerHandler.process(PlayerHandler.java:275)
	at server.Server$1.execute(Server.java:193)
	at server.task.Task.tick(Task.java:102)
	at server.task.TaskScheduler.run(TaskScheduler.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)[/code]

Special java 136
[code=java]			c.removeSpec(12323);[/code]
	at server.oblivion2.player.Client.wear(Client.java:2605)
[code=java]			Special.needSpecial(wearID, targetSlot);[/code]
at server.oblivion2.player.Packets.parseIncomingPackets(Packets.java:5438)
[code=java]at server.oblivion2.player.Packets.parseIncomingPackets(Packets.java:5438)[/code]</description>
    
    <lastBuildDate>Wed, 20 Mar 2013 04:31:05 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Exception encountered while trying to wear something</title>
        <dc:creator><![CDATA[@strucker Strucker]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/strucker">@strucker</a> wrote:</p>
          <blockquote>
              <p>But i don’t know why it’s null, because i got it back just the way it was.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201/3">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201/3</link>
        <pubDate>Wed, 20 Mar 2013 04:31:05 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-509201-3</guid>
        <source url="https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201.rss">Exception encountered while trying to wear something</source>
      </item>
      <item>
        <title>Exception encountered while trying to wear something</title>
        <dc:creator><![CDATA[@Clawz_fury lare69]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/clawz_fury">@Clawz_fury</a> wrote:</p>
          <blockquote>
              <p>any money you aren’t setting the fields properly like I told you to do. That’s why the Client declaration is null and therefore throwing a nullpointerexception.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201/2</link>
        <pubDate>Wed, 20 Mar 2013 04:18:58 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-509201-2</guid>
        <source url="https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201.rss">Exception encountered while trying to wear something</source>
      </item>
      <item>
        <title>Exception encountered while trying to wear something</title>
        <dc:creator><![CDATA[@strucker Strucker]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/strucker">@strucker</a> wrote:</p>
          <blockquote>
              <p>Okay this might sound stupid, i was messing with my stuff cleaning blabla, and i saw the boolean wear and then i said, i’ll move it to wearing.java l0l and then when i moved it it would throw me an exception so i moved it back to the client and then it’s throwing me the same excp…<code>xception encountered while parsing incoming packets from Mr boogie.
java.lang.NullPointerException
	at server.oblivion2.player.Special.needSpecial(Special.java:136)
	at server.oblivion2.player.Client.wear(Client.java:2605)
	at server.oblivion2.player.Packets.parseIncomingPackets(Packets.java:5438)
	at server.oblivion2.player.Client.packetProcess(Client.java:9889)
	at server.oblivion2.player.PlayerHandler.process(PlayerHandler.java:275)
	at server.Server$1.execute(Server.java:193)
	at server.task.Task.tick(Task.java:102)
	at server.task.TaskScheduler.run(TaskScheduler.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)</code></p>
<p>Special java 136</p>
<pre><code class="lang-auto"></code></pre>
<pre><code>at server.oblivion2.player.Client.wear(Client.java:2605)
</code></pre>
<pre><code class="lang-auto"></code></pre>
<p>at server.oblivion2.player.Packets.parseIncomingPackets(Packets.java:5438)</p>
<pre><code class="lang-auto"></code></pre>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201/1</link>
        <pubDate>Wed, 20 Mar 2013 00:38:15 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-509201-1</guid>
        <source url="https://forum.moparisthebest.com/t/exception-encountered-while-trying-to-wear-something/509201.rss">Exception encountered while trying to wear something</source>
      </item>
  </channel>
</rss>
