<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>MySQL error at runtime with my source</title>
    <link>https://forum.moparisthebest.com/t/mysql-error-at-runtime-with-my-source/176233</link>
    <description>hey i run my server and i get this error i just recently added mysql to a server and im new to it so help will be appreicated

ok done that and it got rid of thatt exception but now it throws back this one

[QUOTE]com.mysql.jdbc.CommunicationsException: Communications link failure due to under
lying exception:

** BEGIN NESTED EXCEPTION **

java.net.ConnectException
MESSAGE: Connection timed out: connect

STACKTRACE:

java.net.ConnectException: Connection timed out: connect
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(Unknown Source)
        at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.&lt;init&gt;(Unknown Source)
        at java.net.Socket.&lt;init&gt;(Unknown Source)
        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.ja
va:173)
        at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:267)
        at com.mysql.jdbc.Connection.createNewIO(Connection.java:2739)
        at com.mysql.jdbc.Connection.&lt;init&gt;(Connection.java:1553)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java
:266)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at MySQL.Connect(MySQL.java:55)
        at MySQL.&lt;init&gt;(MySQL.java:20)
        at server.main(server.java:32)


** END NESTED EXCEPTION **[/QUOTE]</description>
    
    <lastBuildDate>Sat, 26 Jan 2008 22:45:41 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/mysql-error-at-runtime-with-my-source/176233.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>MySQL error at runtime with my source</title>
        <dc:creator><![CDATA[@blobboy blobboy]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/blobboy">@blobboy</a> wrote:</p>
          <blockquote>
              <p>hey i run my server and i get this error i just recently added mysql to a server and im new to it so help will be appreicated</p>
<p>ok done that and it got rid of thatt exception but now it throws back this one</p>
<p>[QUOTE]com.mysql.jdbc.CommunicationsException: Communications link failure due to under<br>
lying exception:</p>
<p>** BEGIN NESTED EXCEPTION **</p>
<p>java.net.ConnectException<br>
MESSAGE: Connection timed out: connect</p>
<p>STACKTRACE:</p>
<p>java.net.ConnectException: Connection timed out: connect<br>
at java.net.PlainSocketImpl.socketConnect(Native Method)<br>
at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
at java.net.PlainSocketImpl.connectToAddress(Unknown Source)<br>
at java.net.PlainSocketImpl.connect(Unknown Source)<br>
at java.net.SocksSocketImpl.connect(Unknown Source)<br>
at java.net.Socket.connect(Unknown Source)<br>
at java.net.Socket.connect(Unknown Source)<br>
at java.net.Socket.(Unknown Source)<br>
at java.net.Socket.(Unknown Source)<br>
at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.ja<br>
va:173)<br>
at com.mysql.jdbc.MysqlIO.(MysqlIO.java:267)<br>
at com.mysql.jdbc.Connection.createNewIO(Connection.java:2739)<br>
at com.mysql.jdbc.Connection.(Connection.java:1553)<br>
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java<br>
:266)<br>
at java.sql.DriverManager.getConnection(Unknown Source)<br>
at java.sql.DriverManager.getConnection(Unknown Source)<br>
at MySQL.Connect(MySQL.java:55)<br>
at MySQL.(MySQL.java:20)<br>
at server.main(server.java:32)</p>
<p>** END NESTED EXCEPTION **[/QUOTE]</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/mysql-error-at-runtime-with-my-source/176233/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/mysql-error-at-runtime-with-my-source/176233/1</link>
        <pubDate>Sat, 26 Jan 2008 22:45:41 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-176233-1</guid>
        <source url="https://forum.moparisthebest.com/t/mysql-error-at-runtime-with-my-source/176233.rss">MySQL error at runtime with my source</source>
      </item>
  </channel>
</rss>
