<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Error</title>
    <link>https://forum.moparisthebest.com/t/error/429593</link>
    <description>[code][00:00:05]: Injected FlagMap with 105531 objects covering 208255 tiles in 390ms.
[00:00:05]: listening for connections on port 43594.
[00:00:49]: java.sql.SQLException: Got error 134 from storage engine
[00:00:49]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
[00:00:49]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:1545)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1401)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:2829)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:468)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:2534)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1749)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2159)
[00:00:49]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2548)
[00:00:49]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2477)
[00:00:49]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
[00:00:49]: 	at com.rs2.net.Login.process(Login.java:215)
[00:00:49]: 	at com.rs2.net.Login.read(Login.java:363)
[00:00:49]: 	at com.rs2.net.ConnectionListener.read(ConnectionListener.java:123)
[00:00:49]: 	at com.rs2.net.ConnectionListener.run(ConnectionListener.java:77)
[00:00:49]: 	at java.lang.Thread.run(Unknown Source)
[00:00:49]: Zoft logged in [idx=1, online=1]
[/code]


I don&#39;t know what happened I restarted my PC and now when I run my server it gives me this error...</description>
    
    <lastBuildDate>Tue, 17 Jan 2012 01:49:27 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/error/429593.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Error</title>
        <dc:creator><![CDATA[@Zoft1 Zoft™]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/zoft1">@Zoft1</a> wrote:</p>
          <blockquote>
              <p><code>[00:00:05]: Injected FlagMap with 105531 objects covering 208255 tiles in 390ms.
[00:00:05]: listening for connections on port 43594.
[00:00:49]: java.sql.SQLException: Got error 134 from storage engine
[00:00:49]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
[00:00:49]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:1545)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1401)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:2829)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:468)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:2534)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1749)
[00:00:49]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2159)
[00:00:49]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2548)
[00:00:49]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2477)
[00:00:49]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
[00:00:49]: 	at com.rs2.net.Login.process(Login.java:215)
[00:00:49]: 	at com.rs2.net.Login.read(Login.java:363)
[00:00:49]: 	at com.rs2.net.ConnectionListener.read(ConnectionListener.java:123)
[00:00:49]: 	at com.rs2.net.ConnectionListener.run(ConnectionListener.java:77)
[00:00:49]: 	at java.lang.Thread.run(Unknown Source)
[00:00:49]: Zoft logged in [idx=1, online=1]
</code></p>
<p>I don’t know what happened I restarted my PC and now when I run my server it gives me this error…</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/error/429593/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/error/429593/1</link>
        <pubDate>Tue, 17 Jan 2012 01:49:27 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-429593-1</guid>
        <source url="https://forum.moparisthebest.com/t/error/429593.rss">Error</source>
      </item>
  </channel>
</rss>
