<!DOCTYPE html>
<html lang="en-US">
  
<!-- Mirrored from forum.moparisthebest.com/t/weird-shit/405733 by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 06 Aug 2019 23:30:47 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <title>Weird shit - Runescape - moparisthebest.com</title>
    <meta name="description" content="I was on my server then it dced. Try to log on again and says your already logged in. I restarted the server and it nulled. I restarted again and it was fine but i get this in the run cmd: 

 ler.java:201)
[7/22/11 9:34 &amp;hellip;">
    <meta name="generator" content="Discourse 2.3.2 - https://github.com/discourse/discourse version c587df7e2a03c2962f4c8cefd6f03969bb87d525">
<link rel="icon" type="image/png" href="../../uploads/default/optimized/2X/1/1f0dc167bcf798bdbd70b03bf0fd1bc836e54e1a_2_32x32.png">
<link rel="apple-touch-icon" type="image/png" href="../../uploads/default/optimized/2X/4/41fecb6185fddc2758aeba68c3f8c9c78e26e4ff_2_180x180.png">
<meta name="theme-color" content="#0088cc">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes, viewport-fit=cover">
<link rel="canonical" href="405733.html" />
<script type="application/ld+json">{"@context":"http://schema.org","@type":"WebSite","url":"https://forum.moparisthebest.com","potentialAction":{"@type":"SearchAction","target":"https://forum.moparisthebest.com/search?q={search_term_string}","query-input":"required name=search_term_string"}}</script>
<link rel="search" type="application/opensearchdescription+xml" href="../../opensearch.xml" title="moparisthebest.com Search">

      <link href="../../stylesheets/desktop_1_ec9f75e3d0b2a904642ce53663991837b70cda3334fc.css?__ws=forum.moparisthebest.com" media="all" rel="stylesheet" data-target="desktop" data-theme-id="2"/>
      <link href="../../stylesheets/desktop_theme_2_6707e7ee46ac9f2f0510c29ddd10e8f6ce21c1ae34fc.css?__ws=forum.moparisthebest.com" media="all" rel="stylesheet" data-target="desktop_theme" data-theme-id="2"/>
    
    
      <link rel="alternate" type="application/rss+xml" title="RSS feed of &#39;Weird shit&#39;" href="405733.rss" />
  <meta property="og:site_name" content="moparisthebest.com" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:image" content="https://forum.moparisthebest.com/uploads/default/original/2X/4/41fecb6185fddc2758aeba68c3f8c9c78e26e4ff.png" />
<meta property="og:image" content="https://forum.moparisthebest.com/uploads/default/original/2X/4/41fecb6185fddc2758aeba68c3f8c9c78e26e4ff.png" />
<meta property="og:url" content="https://forum.moparisthebest.com/t/weird-shit/405733" />
<meta name="twitter:url" content="https://forum.moparisthebest.com/t/weird-shit/405733" />
<meta property="og:title" content="Weird shit" />
<meta name="twitter:title" content="Weird shit" />
<meta property="og:description" content="I was on my server then it dced. Try to log on again and says your already logged in. I restarted the server and it nulled. I restarted again and it was fine but i get this in the run cmd:  [code]ler.java:201)  [7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)  [7/22/11 9:34 AM]: java.lang.NullPointerException  [7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)  [7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)  [7/22/11 9:34 AM]:      at server.ut..." />
<meta name="twitter:description" content="I was on my server then it dced. Try to log on again and says your already logged in. I restarted the server and it nulled. I restarted again and it was fine but i get this in the run cmd:  [code]ler.java:201)  [7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)  [7/22/11 9:34 AM]: java.lang.NullPointerException  [7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)  [7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)  [7/22/11 9:34 AM]:      at server.ut..." />
<meta property="article:published_time" content="2011-07-22T16:41:01+00:00" />
<meta property="og:ignore_canonical" content="true" />



    
  </head>
  <body class="crawler">
    
    <header>
      <a href="../../index.html">
          <img src="../../uploads/default/original/2X/3/37bba8fb3bd06c372ab54fa72ec38bf9f8f40b37.gif" alt="moparisthebest.com" id="site-logo" style="max-width: 150px;">
      </a>
    </header>
    <div id="main-outlet" class="wrap">
      <h1 class="crawler-topic-title">
  <a href="405733.html">Weird shit</a>
</h1>

<div id='breadcrumbs'>
    <div id="breadcrumb-0" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"
        itemref="breadcrumb-1"
      >
      <a href="../../c/games.html" itemprop="url" class='badge-wrapper bullet'>
        <span class="badge-category-bg"></span>
        <span itemprop="title" class='category-title'>Games</span>
      </a>
    </div>
    <div id="breadcrumb-1" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"
>
      <a href="../../c/games/runescape.html" itemprop="url" class='badge-wrapper bullet'>
        <span class="badge-category-bg"></span>
        <span itemprop="title" class='category-title'>Runescape</span>
      </a>
    </div>
</div>





  <div itemscope itemtype='http://schema.org/DiscussionForumPosting' class='topic-body crawler-post'>
      <div class='crawler-post-meta'>
        <span class="creator" itemprop="author" itemscope itemtype="http://schema.org/Person">
          <a itemprop="url" href='../../u/coryallen1.html'><span itemprop='name'>coryallen1</span></a>
          
        </span>

        <span class="crawler-post-infos">
            <meta itemprop='datePublished' content='2011-07-22T16:41:01Z'>
            <time itemprop='dateModified' datetime='2016-08-01T13:24:08Z' class='post-time'>
              August 1, 2016,  1:24pm
            </time>
        <span itemprop='position'>#1</span>
        </span>
      </div>
      <div class='post' itemprop='articleBody'>
        <p>I was on my server then it dced. Try to log on again and says your already logged in. I restarted the server and it nulled. I restarted again and it was fine but i get this in the run cmd:</p>
<p>[code]ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,443,709 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,443,709 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[7/22/11 9:34 AM]:      … 16 more<br>
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[7/22/11 9:34 AM]:      … 17 more<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,444,912 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,444,912 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[7/22/11 9:34 AM]:      … 16 more<br>
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[7/22/11 9:34 AM]:      … 17 more<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,446,006 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,446,006 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[7/22/11 9:34 AM]:      … 16 more<br>
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[7/22/11 9:34 AM]:      … 17 more<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
3)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: [REGISTERED]: firstchoice8<br>
[7/22/11 9:34 AM]: cory - actionbutton: 13092<br>
[7/22/11 9:34 AM]: cory - actionbutton: 13218<br>
[7/22/11 9:35 AM]: trade reset<br>
[7/22/11 9:36 AM]: trade reset[/code]</p>
<p>Ik this bit means my IP has been black listed by my webhost so they are blocking remote mySQL connections.</p>
<p><code>The last packet successfully received from the server was 1,311,352,446,006 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.</code></p>
<p>I haven’t got a clue about the rest. Could this whole error be caused by my IP being black listed?</p>
      </div>

      <meta itemprop='headline' content='Weird shit'>

      <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
         <meta itemprop="interactionType" content="http://schema.org/LikeAction"/>
         <meta itemprop="userInteractionCount" content="0" />
         <span class='post-likes'></span>
       </div>

       <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
          <meta itemprop="interactionType" content="http://schema.org/CommentAction"/>
          <meta itemprop="userInteractionCount" content="0" />
        </div>


  </div>






    </div>
    <footer class="container wrap">
      <nav class='crawler-nav' itemscope itemtype='http://schema.org/SiteNavigationElement'>
        <ul>
        <li itemprop="name"><a href='../../index.html' itemprop="url">Home </a></li>
        <li itemprop="name"><a href='../../categories.html' itemprop="url">Categories </a></li>
        <li itemprop="name"><a href='../../guidelines.html' itemprop="url">FAQ/Guidelines </a></li>
        <li itemprop="name"><a href='../../tos.html' itemprop="url">Terms of Service </a></li>
        <li itemprop="name"><a href='../../privacy.html' itemprop="url">Privacy Policy </a></li>
        </ul>
      </nav>
      <p class='powered-by-link'>Powered by <a href="https://www.discourse.org/">Discourse</a>, best viewed with JavaScript enabled</p>
    </footer>
    
  </body>
  

<!-- Mirrored from forum.moparisthebest.com/t/weird-shit/405733 by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 06 Aug 2019 23:30:47 GMT -->
</html>
