<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Weird shit</title>
    <link>https://forum.moparisthebest.com/t/weird-shit/405733</link>
    <description>I was on my server then it dced. Try to log on again and says your already logged in. I restarted the server and it nulled. I restarted again and it was fine but i get this in the run cmd:


[code]ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: java.lang.NullPointerException
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,311,352,443,709 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,311,352,443,709 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[7/22/11 9:34 AM]:      ... 16 more
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)

[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[7/22/11 9:34 AM]:      ... 17 more
[7/22/11 9:34 AM]: java.lang.NullPointerException
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: java.lang.NullPointerException
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,311,352,444,912 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,311,352,444,912 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[7/22/11 9:34 AM]:      ... 16 more
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)

[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[7/22/11 9:34 AM]:      ... 17 more
[7/22/11 9:34 AM]: java.lang.NullPointerException
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: java.lang.NullPointerException
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm
unications link failure

The last packet successfully received from the server was 1,311,352,446,006 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce
ption: Communications link failure

The last packet successfully received from the server was 1,311,352,446,006 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance
(Unknown Source)
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[7/22/11 9:34 AM]:      ... 16 more
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con
nect
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)

[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou
rce)
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[7/22/11 9:34 AM]:      at java.net.Socket.&lt;init&gt;(Unknown Source)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[7/22/11 9:34 AM]:      ... 17 more
[7/22/11 9:34 AM]: java.lang.NullPointerException
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
2)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: java.lang.NullPointerException
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55
3)
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand
ler.java:201)
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)
[7/22/11 9:34 AM]: [REGISTERED]: firstchoice8
[7/22/11 9:34 AM]: cory - actionbutton: 13092
[7/22/11 9:34 AM]: cory - actionbutton: 13218
[7/22/11 9:35 AM]: trade reset
[7/22/11 9:36 AM]: trade reset[/code]


Ik this bit means my IP has been black listed by my webhost so they are blocking remote mySQL connections.

[code]The last packet successfully received from the server was 1,311,352,446,006 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.[/code]

I haven&#39;t got a clue about the rest. Could this whole error be caused by my IP being black listed?</description>
    
    <lastBuildDate>Fri, 22 Jul 2011 16:41:01 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/weird-shit/405733.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Weird shit</title>
        <dc:creator><![CDATA[@coryallen1 coryallen1]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/coryallen1">@coryallen1</a> wrote:</p>
          <blockquote>
              <p>I was on my server then it dced. Try to log on again and says your already logged in. I restarted the server and it nulled. I restarted again and it was fine but i get this in the run cmd:</p>
<p>[code]ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,443,709 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,443,709 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[7/22/11 9:34 AM]:      … 16 more<br>
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[7/22/11 9:34 AM]:      … 17 more<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:53)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,444,912 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,444,912 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[7/22/11 9:34 AM]:      … 16 more<br>
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[7/22/11 9:34 AM]:      … 17 more<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:54)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:33)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Comm<br>
unications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,446,006 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor4.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.sql.DriverManager.getConnection(Unknown Source)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.createConnection(SQL.java:17)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:34)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExce<br>
ption: Communications link failure</p>
<p>The last packet successfully received from the server was 1,311,352,446,006 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[7/22/11 9:34 AM]:      at sun.reflect.GeneratedConstructorAccessor2.newInstance<br>
(Unknown Source)<br>
[7/22/11 9:34 AM]:      at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[7/22/11 9:34 AM]:      … 16 more<br>
[7/22/11 9:34 AM]: Caused by: java.net.ConnectException: Connection refused: con<br>
nect<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[7/22/11 9:34 AM]:      at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.connect(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at java.net.Socket.(Unknown Source)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[7/22/11 9:34 AM]:      at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[7/22/11 9:34 AM]:      … 17 more<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.query(SQL.java:29)<br>
[7/22/11 9:34 AM]:      at server.util.SQL.saveHighScores(SQL.java:55)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
2)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: java.lang.NullPointerException<br>
[7/22/11 9:34 AM]:      at server.util.SQL.destroyConnection(SQL.java:42)<br>
[7/22/11 9:34 AM]:      at server.model.players.Client.initialize(Client.java:55<br>
3)<br>
[7/22/11 9:34 AM]:      at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:201)<br>
[7/22/11 9:34 AM]:      at server.Server.main(Server.java:174)<br>
[7/22/11 9:34 AM]: [REGISTERED]: firstchoice8<br>
[7/22/11 9:34 AM]: cory - actionbutton: 13092<br>
[7/22/11 9:34 AM]: cory - actionbutton: 13218<br>
[7/22/11 9:35 AM]: trade reset<br>
[7/22/11 9:36 AM]: trade reset[/code]</p>
<p>Ik this bit means my IP has been black listed by my webhost so they are blocking remote mySQL connections.</p>
<p><code>The last packet successfully received from the server was 1,311,352,446,006 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.</code></p>
<p>I haven’t got a clue about the rest. Could this whole error be caused by my IP being black listed?</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/weird-shit/405733/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/weird-shit/405733/1</link>
        <pubDate>Fri, 22 Jul 2011 16:41:01 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-405733-1</guid>
        <source url="https://forum.moparisthebest.com/t/weird-shit/405733.rss">Weird shit</source>
      </item>
  </channel>
</rss>
