<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Dementhium Login Problem</title>
    <link>https://forum.moparisthebest.com/t/dementhium-login-problem/444325</link>
    <description>My Source will run but it won&#39;t run correctly. When I try to run it on my computer, it says running cache and a lot of other things also. When I try to run the source on the VPS i get this.. And yes I did put the cache in the correct spot on the source, and obviously it does connect to the source when your logging in because i get errors. 

When I try to load the Source on VPS it just says &quot;server bound to Port 43594.&quot; 

When I try to connect to the server it says &quot;Error loading your profile. Please contact customer support.&quot; 

In the source it says. [QUOTE]&quot;
Server bound to port - 43594
java.io.FileNotFoundException: C:\Users\root\ecogames\testaccount.bin (The syste
m cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.&lt;init&gt;(Unknown Source)
        at java.io.FileOutputStream.&lt;init&gt;(Unknown Source)
        at org.dementhium.io.FileUtilities.writeBufferToFile(FileUtilities.java:
38)
        at org.dementhium.io.PlayerLoader.save(PlayerLoader.java:150)
        at org.dementhium.io.PlayerLoader.load(PlayerLoader.java:107)
        at org.dementhium.model.World$1.run(World.java:212)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.io.FileNotFoundException: C:\Users\root\ecogames\testaccount.bin (The syste
m cannot find the path specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.&lt;init&gt;(Unknown Source)
        at java.io.FileInputStream.&lt;init&gt;(Unknown Source)
        at org.dementhium.io.FileUtilities.fileBuffer(FileUtilities.java:20)
        at org.dementhium.io.PlayerLoader.load(PlayerLoader.java:133)
        at org.dementhium.model.World$1.run(World.java:218)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[/Quote]

Inside of saving errors..
[Quote]
java.io.FileOutputStream.open(Native Method)
java.io.FileOutputStream.&lt;init&gt;(Unknown Source)
java.io.FileOutputStream.&lt;init&gt;(Unknown Source)
org.dementhium.io.FileUtilities.writeBufferToFile(FileUtilities.java:38)
org.dementhium.io.PlayerLoader.save(PlayerLoader.java:150)
org.dementhium.io.PlayerLoader.load(PlayerLoader.java:107)
org.dementhium.model.World$1.run(World.java:212)
java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)
Player testaccount
[/quote]

Anyone know the problem why my source won&#39;t correctly run on the VPS?</description>
    
    <lastBuildDate>Fri, 29 Jun 2012 13:47:29 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/dementhium-login-problem/444325.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Dementhium Login Problem</title>
        <dc:creator><![CDATA[@sniickerize sniickerize]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/sniickerize">@sniickerize</a> wrote:</p>
          <blockquote>
              <p>Pay me and ill do the job done.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/dementhium-login-problem/444325/3">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/dementhium-login-problem/444325/3</link>
        <pubDate>Fri, 29 Jun 2012 13:47:29 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-444325-3</guid>
        <source url="https://forum.moparisthebest.com/t/dementhium-login-problem/444325.rss">Dementhium Login Problem</source>
      </item>
      <item>
        <title>Dementhium Login Problem</title>
        <dc:creator><![CDATA[@Ashi Ashi]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/ashi">@Ashi</a> wrote:</p>
          <blockquote>
              <p>This may help not sure if it will fix problem but go to your root folder and create a new folder called ecogames<br>
then try running your server again.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/dementhium-login-problem/444325/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/dementhium-login-problem/444325/2</link>
        <pubDate>Fri, 08 Jun 2012 21:28:08 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-444325-2</guid>
        <source url="https://forum.moparisthebest.com/t/dementhium-login-problem/444325.rss">Dementhium Login Problem</source>
      </item>
      <item>
        <title>Dementhium Login Problem</title>
        <dc:creator><![CDATA[@giveitup giveitup]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/giveitup">@giveitup</a> wrote:</p>
          <blockquote>
              <p>My Source will run but it won’t run correctly. When I try to run it on my computer, it says running cache and a lot of other things also. When I try to run the source on the VPS i get this… And yes I did put the cache in the correct spot on the source, and obviously it does connect to the source when your logging in because i get errors.</p>
<p>When I try to load the Source on VPS it just says “server bound to Port 43594.”</p>
<p>When I try to connect to the server it says “Error loading your profile. Please contact customer support.”</p>
<p>In the source it says. [QUOTE]"<br>
Server bound to port - 43594<br>
java.io.FileNotFoundException: C:\Users\root\ecogames\testaccount.bin (The syste<br>
m cannot find the path specified)<br>
at java.io.FileOutputStream.open(Native Method)<br>
at java.io.FileOutputStream.(Unknown Source)<br>
at java.io.FileOutputStream.(Unknown Source)<br>
at org.dementhium.io.FileUtilities.writeBufferToFile(FileUtilities.java:<br>
38)<br>
at org.dementhium.io.PlayerLoader.save(PlayerLoader.java:150)<br>
at org.dementhium.io.PlayerLoader.load(PlayerLoader.java:107)<br>
at org.dementhium.model.World$1.run(World.java:212)<br>
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)<br>
at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)<br>
at java.util.concurrent.FutureTask.run(Unknown Source)<br>
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br>
at java.lang.Thread.run(Unknown Source)<br>
java.io.FileNotFoundException: C:\Users\root\ecogames\testaccount.bin (The syste<br>
m cannot find the path specified)<br>
at java.io.FileInputStream.open(Native Method)<br>
at java.io.FileInputStream.(Unknown Source)<br>
at java.io.FileInputStream.(Unknown Source)<br>
at org.dementhium.io.FileUtilities.fileBuffer(FileUtilities.java:20)<br>
at org.dementhium.io.PlayerLoader.load(PlayerLoader.java:133)<br>
at org.dementhium.model.World$1.run(World.java:218)<br>
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)<br>
at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)<br>
at java.util.concurrent.FutureTask.run(Unknown Source)<br>
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br>
at java.lang.Thread.run(Unknown Source)<br>
[/Quote]</p>
<p>Inside of saving errors…</p>
<aside class="quote">
<blockquote>
<p>java.io.FileOutputStream.open(Native Method)<br>
java.io.FileOutputStream.(Unknown Source)<br>
java.io.FileOutputStream.(Unknown Source)<br>
org.dementhium.io.FileUtilities.writeBufferToFile(FileUtilities.java:38)<br>
org.dementhium.io.PlayerLoader.save(PlayerLoader.java:150)<br>
org.dementhium.io.PlayerLoader.load(PlayerLoader.java:107)<br>
org.dementhium.model.World$1.run(World.java:212)<br>
java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)<br>
java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)<br>
java.util.concurrent.FutureTask.run(Unknown Source)<br>
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br>
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br>
java.lang.Thread.run(Unknown Source)<br>
Player testaccount</p>
</blockquote>
</aside>
<p>Anyone know the problem why my source won’t correctly run on the VPS?</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/dementhium-login-problem/444325/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/dementhium-login-problem/444325/1</link>
        <pubDate>Thu, 07 Jun 2012 21:50:38 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-444325-1</guid>
        <source url="https://forum.moparisthebest.com/t/dementhium-login-problem/444325.rss">Dementhium Login Problem</source>
      </item>
  </channel>
</rss>
