<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>[PI] Error, ScriptManager</title>
    <link>https://forum.moparisthebest.com/t/pi-error-scriptmanager/390735</link>
    <description>So, when I compile everything is fine and dandy. BUT, when I run the server it loads fine then right at the end I get this...

[code][4/12/11 9:40 PM]: Launching InProgresse 
[4/12/11 9:40 PM]: Loading scripts... 
.\Data\scripts\player\eat\eat.pyscript: 
.\Data\scripts\player\items\spade.pypt: 
.\Data\scripts\player\npc\npc1.pyscript:
 .\Data\scripts\player\npc\npc2.pyscript:
 .\Data\scripts\player\npc\npc3.pyscript:
 .\Data\scripts\player\objects\objectclick1.py
 .\Data\scripts\player\objects\objectclick2.py 
.\Data\scripts\player\objects\objectclick3.py 
.\Data\scripts\player\skills\herblore.py 
.\Data\scripts\player\skills\mining.py 
[4/12/11 9:40 PM]: Exception in thread &quot;main&quot; Traceback (innermost last): 
File &quot;&lt;iostream&gt;&quot;, line 4, in ? 
ImportError: no module named random Press any key to continue . . .[/code]

I&#39;&#39;m assuming it has to with a file named Random.</description>
    
    <lastBuildDate>Wed, 13 Apr 2011 06:01:12 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/pi-error-scriptmanager/390735.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>[PI] Error, ScriptManager</title>
        <dc:creator><![CDATA[@kriskuhar kriskuhar]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/kriskuhar">@kriskuhar</a> wrote:</p>
          <blockquote>
              <p>So, when I compile everything is fine and dandy. BUT, when I run the server it loads fine then right at the end I get this…</p>
<p><code>[4/12/11 9:40 PM]: Launching InProgresse 
[4/12/11 9:40 PM]: Loading scripts... 
.\Data\scripts\player\eat\eat.pyscript: 
.\Data\scripts\player\items\spade.pypt: 
.\Data\scripts\player\npc\npc1.pyscript:
 .\Data\scripts\player\npc\npc2.pyscript:
 .\Data\scripts\player\npc\npc3.pyscript:
 .\Data\scripts\player\objects\objectclick1.py
 .\Data\scripts\player\objects\objectclick2.py 
.\Data\scripts\player\objects\objectclick3.py 
.\Data\scripts\player\skills\herblore.py 
.\Data\scripts\player\skills\mining.py 
[4/12/11 9:40 PM]: Exception in thread "main" Traceback (innermost last): 
File "&lt;iostream&gt;", line 4, in ? 
ImportError: no module named random Press any key to continue . . .</code></p>
<p>I’'m assuming it has to with a file named Random.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/pi-error-scriptmanager/390735/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/pi-error-scriptmanager/390735/1</link>
        <pubDate>Wed, 13 Apr 2011 06:01:12 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-390735-1</guid>
        <source url="https://forum.moparisthebest.com/t/pi-error-scriptmanager/390735.rss">[PI] Error, ScriptManager</source>
      </item>
  </channel>
</rss>
