<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Help with Hyperion 459 needed. EDIT</title>
    <link>https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282</link>
    <description>EDIT:
[code]SEVERE: Error starting Hyperion.
java.util.concurrent.ExecutionException: org.hyperion.cache.InvalidCacheException: java.io.IOException: Unexpected next cache id.
	at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at org.hyperion.util.BlockingExecutorService.waitForPendingTasks(BlockingExecutorService.java:50)
	at org.hyperion.rs2.RS2Server.start(RS2Server.java:74)
	at org.hyperion.Server.main(Server.java:36)
Caused by: org.hyperion.cache.InvalidCacheException: java.io.IOException: Unexpected next cache id.
	at org.hyperion.cache.Cache.&lt;init&gt;(Cache.java:86)
	at org.hyperion.rs2.model.ObjectManager.load(ObjectManager.java:44)
	at org.hyperion.rs2.model.World$2.call(World.java:125)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Unexpected next cache id.
	at org.hyperion.cache.Cache.getFile(Cache.java:161)
	at org.hyperion.cache.index.IndexTable.&lt;init&gt;(IndexTable.java:35)
	at org.hyperion.cache.Cache.&lt;init&gt;(Cache.java:82)
	... 7 more[/code]

Help please? No flame.</description>
    
    <lastBuildDate>Sat, 01 Jan 2011 18:44:42 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Help with Hyperion 459 needed. EDIT</title>
        <dc:creator><![CDATA[@Phaze_One Fuscate]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/phaze_one">@Phaze_One</a> wrote:</p>
          <blockquote>
              <p>The error explains everything?</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282/2</link>
        <pubDate>Sat, 01 Jan 2011 18:44:42 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-376282-2</guid>
        <source url="https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282.rss">Help with Hyperion 459 needed. EDIT</source>
      </item>
      <item>
        <title>Help with Hyperion 459 needed. EDIT</title>
        <dc:creator><![CDATA[@godundeadscape godundeadscape]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/godundeadscape">@godundeadscape</a> wrote:</p>
          <blockquote>
              <p>EDIT:</p>
<p><code>SEVERE: Error starting Hyperion.
java.util.concurrent.ExecutionException: org.hyperion.cache.InvalidCacheException: java.io.IOException: Unexpected next cache id.
	at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at org.hyperion.util.BlockingExecutorService.waitForPendingTasks(BlockingExecutorService.java:50)
	at org.hyperion.rs2.RS2Server.start(RS2Server.java:74)
	at org.hyperion.Server.main(Server.java:36)
Caused by: org.hyperion.cache.InvalidCacheException: java.io.IOException: Unexpected next cache id.
	at org.hyperion.cache.Cache.&lt;init&gt;(Cache.java:86)
	at org.hyperion.rs2.model.ObjectManager.load(ObjectManager.java:44)
	at org.hyperion.rs2.model.World$2.call(World.java:125)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Unexpected next cache id.
	at org.hyperion.cache.Cache.getFile(Cache.java:161)
	at org.hyperion.cache.index.IndexTable.&lt;init&gt;(IndexTable.java:35)
	at org.hyperion.cache.Cache.&lt;init&gt;(Cache.java:82)
	... 7 more</code></p>
<p>Help please? No flame.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282/1</link>
        <pubDate>Sat, 01 Jan 2011 18:40:12 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-376282-1</guid>
        <source url="https://forum.moparisthebest.com/t/help-with-hyperion-459-needed-edit/376282.rss">Help with Hyperion 459 needed. EDIT</source>
      </item>
  </channel>
</rss>
