<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Mysql help ? PI</title>
    <link>https://forum.moparisthebest.com/t/mysql-help-pi/411767</link>
    <description>im trying to set up mysql for highscores on my server it compiles fine but like 5 mins after startup it just gives up and gives me this message im lost lol any ideas ?

[code][23/08/11 22:37]: Launching KushZone...
[23/08/11 22:37]: Server listening on port kushzone.no-ip.info:43594
[23/08/11 22:38]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Commu
nications link failure

The last packet successfully received from the server was 1,314,135,514,831 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[23/08/11 22:38]:       at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[23/08/11 22:38]:       at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)
[23/08/11 22:38]:       at server.util.SQL.createConnection(SQL.java:17)
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13
03)
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand
ler.java:186)
[23/08/11 22:38]:       at server.Server.main(Server.java:162)
[23/08/11 22:38]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExcep
tion: Communications link failure

The last packet successfully received from the server was 1,314,135,514,785 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[23/08/11 22:38]:       ... 15 more
[23/08/11 22:38]: Caused by: java.net.ConnectException: Connection timed out: co
nnect
[23/08/11 22:38]:       at java.net.PlainSocketImpl.socketConnect(Native Method)

[23/08/11 22:38]:       at java.net.PlainSocketImpl.doConnect(Unknown Source)
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connectToAddress(Unknown Sou
rce)
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.SocksSocketImpl.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.&lt;init&gt;(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.&lt;init&gt;(Unknown Source)
[23/08/11 22:38]:       at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[23/08/11 22:38]:       ... 16 more
[23/08/11 22:38]: java.lang.NullPointerException
[23/08/11 22:38]:       at server.util.SQL.destroyConnection(SQL.java:42)
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:33)
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:52)
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13
04)
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand
ler.java:186)
[23/08/11 22:38]:       at server.Server.main(Server.java:162)
[23/08/11 22:38]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Commu
nications link failure

The last packet successfully received from the server was 1,314,135,535,915 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2214)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.j
ava:773)
[23/08/11 22:38]:       at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection
.java:46)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI
mpl.java:352)
[23/08/11 22:38]:       at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist
eringDriver.java:282)
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)
[23/08/11 22:38]:       at server.util.SQL.createConnection(SQL.java:17)
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:34)
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:52)
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13
04)
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand
ler.java:186)
[23/08/11 22:38]:       at server.Server.main(Server.java:162)
[23/08/11 22:38]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExcep
tion: Communications link failure

The last packet successfully received from the server was 1,314,135,535,915 mill
iseconds ago.  The last packet sent successfully to the server was 0 millisecond
s ago.
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
0(Native Method)
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance
(Unknown Source)
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(Unknown Source)
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou
rce)
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1074)
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:341)
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI
mpl.java:2137)
[23/08/11 22:38]:       ... 17 more
[23/08/11 22:38]: Caused by: java.net.ConnectException: Connection timed out: co
nnect
[23/08/11 22:38]:       at java.net.PlainSocketImpl.socketConnect(Native Method)

[23/08/11 22:38]:       at java.net.PlainSocketImpl.doConnect(Unknown Source)
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connectToAddress(Unknown Sou
rce)
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.SocksSocketImpl.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.&lt;init&gt;(Unknown Source)
[23/08/11 22:38]:       at java.net.Socket.&lt;init&gt;(Unknown Source)
[23/08/11 22:38]:       at com.mysql.jdbc.StandardSocketFactory.connect(Standard
SocketFactory.java:253)
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:290)
[23/08/11 22:38]:       ... 18 more
[23/08/11 22:38]: java.lang.NullPointerException
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:29)
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:52)
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13
04)
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand
ler.java:186)
[23/08/11 22:38]:       at server.Server.main(Server.java:162)
[23/08/11 22:38]: java.lang.NullPointerException
[23/08/11 22:38]:       at server.util.SQL.destroyConnection(SQL.java:42)
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:33)
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:53)
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13
04)
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand
ler.java:186)
[23/08/11 22:38]:       at server.Server.main(Server.java:162)
[/code]</description>
    
    <lastBuildDate>Sat, 03 Aug 2013 05:01:31 +0000</lastBuildDate>
    <category>Runescape</category>
    <atom:link href="https://forum.moparisthebest.com/t/mysql-help-pi/411767.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Mysql help ? PI</title>
        <dc:creator><![CDATA[@killemquick0 killemquick0]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/killemquick0">@killemquick0</a> wrote:</p>
          <blockquote>
              <aside class="quote quote-modified" data-post="3" data-topic="411767">
<div class="title">
<div class="quote-controls"></div>
<img alt width="20" height="20" src="https://forum.moparisthebest.com/letter_avatar/pwnd/40/5_e05bb34c421432ee4d40de30c10af3e5.png" class="avatar"> Pwnd:</div>
<blockquote>
<p>NullPointerException means you’re trying to ask for data that isn’t there.  Check out the lines that the trace gives you and search back to where the problem may lie. </p>
</blockquote>
</aside>
<p>The error happens completely randomly for me. It appears to be the communication link for sending and receiving MySql information.</p>
<p>I just added HighScores, and like I said this error is completely random, and not very often, so it must be a sync error not a coding error.</p>
<p>If there any way to declare this error to return, or try again instead of making an error?</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/mysql-help-pi/411767/4">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/mysql-help-pi/411767/4</link>
        <pubDate>Sat, 03 Aug 2013 05:01:31 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-411767-4</guid>
        <source url="https://forum.moparisthebest.com/t/mysql-help-pi/411767.rss">Mysql help ? PI</source>
      </item>
      <item>
        <title>Mysql help ? PI</title>
        <dc:creator><![CDATA[@Pwnd Pwnd]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/pwnd">@Pwnd</a> wrote:</p>
          <blockquote>
              <p>NullPointerException means you’re trying to ask for data that isn’t there.  Check out the lines that the trace gives you and search back to where the problem may lie.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/mysql-help-pi/411767/3">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/mysql-help-pi/411767/3</link>
        <pubDate>Sat, 03 Aug 2013 03:08:47 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-411767-3</guid>
        <source url="https://forum.moparisthebest.com/t/mysql-help-pi/411767.rss">Mysql help ? PI</source>
      </item>
      <item>
        <title>Mysql help ? PI</title>
        <dc:creator><![CDATA[@killemquick0 killemquick0]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/killemquick0">@killemquick0</a> wrote:</p>
          <blockquote>
              <p>same problem, would greatly appreciate an explanation or fix.</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/mysql-help-pi/411767/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/mysql-help-pi/411767/2</link>
        <pubDate>Sat, 03 Aug 2013 01:06:04 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-411767-2</guid>
        <source url="https://forum.moparisthebest.com/t/mysql-help-pi/411767.rss">Mysql help ? PI</source>
      </item>
      <item>
        <title>Mysql help ? PI</title>
        <dc:creator><![CDATA[@_tyco +tyco+]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://forum.moparisthebest.com/u/_tyco">@_tyco</a> wrote:</p>
          <blockquote>
              <p>im trying to set up mysql for highscores on my server it compiles fine but like 5 mins after startup it just gives up and gives me this message im lost lol any ideas ?</p>
<p>[code][23/08/11 22:37]: Launching KushZone…<br>
[23/08/11 22:37]: Server listening on port kushzone.no-ip.info:43594<br>
[23/08/11 22:38]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Commu<br>
nications link failure</p>
<p>The last packet successfully received from the server was 1,314,135,514,831 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)<br>
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)<br>
[23/08/11 22:38]:       at server.util.SQL.createConnection(SQL.java:17)<br>
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13<br>
03)<br>
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:186)<br>
[23/08/11 22:38]:       at server.Server.main(Server.java:162)<br>
[23/08/11 22:38]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExcep<br>
tion: Communications link failure</p>
<p>The last packet successfully received from the server was 1,314,135,514,785 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[23/08/11 22:38]:       … 15 more<br>
[23/08/11 22:38]: Caused by: java.net.ConnectException: Connection timed out: co<br>
nnect<br>
[23/08/11 22:38]:       at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[23/08/11 22:38]:       at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.(Unknown Source)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[23/08/11 22:38]:       … 16 more<br>
[23/08/11 22:38]: java.lang.NullPointerException<br>
[23/08/11 22:38]:       at server.util.SQL.destroyConnection(SQL.java:42)<br>
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:33)<br>
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:52)<br>
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13<br>
04)<br>
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:186)<br>
[23/08/11 22:38]:       at server.Server.main(Server.java:162)<br>
[23/08/11 22:38]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Commu<br>
nications link failure</p>
<p>The last packet successfully received from the server was 1,314,135,535,915 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2214)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.(ConnectionImpl.j<br>
ava:773)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.JDBC4Connection.(JDBC4Connection<br>
.java:46)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionI<br>
mpl.java:352)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegist<br>
eringDriver.java:282)<br>
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)<br>
[23/08/11 22:38]:       at java.sql.DriverManager.getConnection(Unknown Source)<br>
[23/08/11 22:38]:       at server.util.SQL.createConnection(SQL.java:17)<br>
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:34)<br>
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:52)<br>
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13<br>
04)<br>
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:186)<br>
[23/08/11 22:38]:       at server.Server.main(Server.java:162)<br>
[23/08/11 22:38]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsExcep<br>
tion: Communications link failure</p>
<p>The last packet successfully received from the server was 1,314,135,535,915 mill<br>
iseconds ago.  The last packet sent successfully to the server was 0 millisecond<br>
s ago.<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
0(Native Method)<br>
[23/08/11 22:38]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance<br>
(Unknown Source)<br>
[23/08/11 22:38]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInst<br>
ance(Unknown Source)<br>
[23/08/11 22:38]:       at java.lang.reflect.Constructor.newInstance(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.SQLError.createCommunicationsException<br>
(SQLError.java:1074)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.(MysqlIO.java:341)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionI<br>
mpl.java:2137)<br>
[23/08/11 22:38]:       … 17 more<br>
[23/08/11 22:38]: Caused by: java.net.ConnectException: Connection timed out: co<br>
nnect<br>
[23/08/11 22:38]:       at java.net.PlainSocketImpl.socketConnect(Native Method)</p>
<p>[23/08/11 22:38]:       at java.net.PlainSocketImpl.doConnect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connectToAddress(Unknown Sou<br>
rce)<br>
[23/08/11 22:38]:       at java.net.PlainSocketImpl.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.SocksSocketImpl.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.connect(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.(Unknown Source)<br>
[23/08/11 22:38]:       at java.net.Socket.(Unknown Source)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.StandardSocketFactory.connect(Standard<br>
SocketFactory.java:253)<br>
[23/08/11 22:38]:       at com.mysql.jdbc.MysqlIO.(MysqlIO.java:290)<br>
[23/08/11 22:38]:       … 18 more<br>
[23/08/11 22:38]: java.lang.NullPointerException<br>
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:29)<br>
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:52)<br>
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13<br>
04)<br>
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:186)<br>
[23/08/11 22:38]:       at server.Server.main(Server.java:162)<br>
[23/08/11 22:38]: java.lang.NullPointerException<br>
[23/08/11 22:38]:       at server.util.SQL.destroyConnection(SQL.java:42)<br>
[23/08/11 22:38]:       at server.util.SQL.query(SQL.java:33)<br>
[23/08/11 22:38]:       at server.util.SQL.saveHighScores(SQL.java:53)<br>
[23/08/11 22:38]:       at server.model.players.Client.initialize(Client.java:13<br>
04)<br>
[23/08/11 22:38]:       at server.model.players.PlayerHandler.process(PlayerHand<br>
ler.java:186)<br>
[23/08/11 22:38]:       at server.Server.main(Server.java:162)<br>
[/code]</p>
          </blockquote>
          <p><a href="https://forum.moparisthebest.com/t/mysql-help-pi/411767/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.moparisthebest.com/t/mysql-help-pi/411767/1</link>
        <pubDate>Tue, 23 Aug 2011 21:42:20 +0000</pubDate>
        <guid isPermaLink="false">forum.moparisthebest.com-post-411767-1</guid>
        <source url="https://forum.moparisthebest.com/t/mysql-help-pi/411767.rss">Mysql help ? PI</source>
      </item>
  </channel>
</rss>
